import Head from 'next/head'
import Image from 'next/image'
import Project from '../components/Project'

//code
console.log("Hello mister Inspect Element")



export default function Home() {
  return (
    <div className="bg-gradient-to-r from-cyan-500 to-blue-500">
      <div className="flex justify-center text-center align-middle">
        <Head>
          <title>Ditz LandingPage</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="font-sans text-white">
          <h1 className="text-2xl font-bold">
            Welcome to the Ditz LandingPage
          </h1>

          <p className="text-xl">
            Click on any of my project!
          </p>
        </main>
      </div>


      {/*Project List */}
      <div className="flex justify-center">
        <div className="gap-x-10 gap-y-10 justify-center grid grid-cols-4">
          <Project title="Test" description="test" imgSrc={"/../public/favicon.ico"} codingLang={"css"} linkUrl={"https://ditz33.xyz/"}/>
          <Project title="Test" description="test" imgSrc={"/../public/favicon.ico"} codingLang={"css"} linkUrl={"https://ditz33.xyz/"}/>
          <Project title="Test" description="test" imgSrc={"/../public/favicon.ico"} codingLang={"css"} linkUrl={"https://ditz33.xyz/"}/>
          <Project title="Test" description="test" imgSrc={"/../public/favicon.ico"} codingLang={"css"} linkUrl={"https://ditz33.xyz/"}/>
          <Project title="Test" description="test" imgSrc={"/../public/favicon.ico"} codingLang={"css"} linkUrl={"https://ditz33.xyz/"}/>
          <Project title="Test" description="test" imgSrc={"/../public/favicon.ico"} codingLang={"css"} linkUrl={"https://ditz33.xyz/"}/>
          <Project title="Test" description="test" imgSrc={"/../public/favicon.ico"} codingLang={"css"} linkUrl={"https://ditz33.xyz/"}/>
        </div>
      </div>
    </div>
  )
}
