import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Ditz LandingPage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="">
          Welcome to the Ditz LandingPage
        </h1>

        <p className=''>
          Click here on any project!
        </p>
      </main>
    </div>
  )
}
